//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTCService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/UTCService")]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BrandField;
        
        private string CarStatusField;
        
        private string CarTypeField;
        
        private string ColorField;
        
        private string FuelField;
        
        private int IdField;
        
        private int MileageField;
        
        private string ModelField;
        
        private int SeatsField;
        
        private int TotalCostField;
        
        private int YearOfProductionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarStatus
        {
            get
            {
                return this.CarStatusField;
            }
            set
            {
                this.CarStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarType
        {
            get
            {
                return this.CarTypeField;
            }
            set
            {
                this.CarTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuel
        {
            get
            {
                return this.FuelField;
            }
            set
            {
                this.FuelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seats
        {
            get
            {
                return this.SeatsField;
            }
            set
            {
                this.SeatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearOfProduction
        {
            get
            {
                return this.YearOfProductionField;
            }
            set
            {
                this.YearOfProductionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICarService")]
public interface ICarService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCars", ReplyAction="http://tempuri.org/ICarService/GetCarsResponse")]
    UTCService.Car[] GetCars();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCars", ReplyAction="http://tempuri.org/ICarService/GetCarsResponse")]
    System.Threading.Tasks.Task<UTCService.Car[]> GetCarsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddCar", ReplyAction="http://tempuri.org/ICarService/AddCarResponse")]
    void AddCar(UTCService.Car newCar);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/AddCar", ReplyAction="http://tempuri.org/ICarService/AddCarResponse")]
    System.Threading.Tasks.Task AddCarAsync(UTCService.Car newCar);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateCar", ReplyAction="http://tempuri.org/ICarService/UpdateCarResponse")]
    void UpdateCar(UTCService.Car newCar);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/UpdateCar", ReplyAction="http://tempuri.org/ICarService/UpdateCarResponse")]
    System.Threading.Tasks.Task UpdateCarAsync(UTCService.Car newCar);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteCar", ReplyAction="http://tempuri.org/ICarService/DeleteCarResponse")]
    void DeleteCar(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/DeleteCar", ReplyAction="http://tempuri.org/ICarService/DeleteCarResponse")]
    System.Threading.Tasks.Task DeleteCarAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICarServiceChannel : ICarService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CarServiceClient : System.ServiceModel.ClientBase<ICarService>, ICarService
{
    
    public CarServiceClient()
    {
    }
    
    public CarServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public UTCService.Car[] GetCars()
    {
        return base.Channel.GetCars();
    }
    
    public System.Threading.Tasks.Task<UTCService.Car[]> GetCarsAsync()
    {
        return base.Channel.GetCarsAsync();
    }
    
    public void AddCar(UTCService.Car newCar)
    {
        base.Channel.AddCar(newCar);
    }
    
    public System.Threading.Tasks.Task AddCarAsync(UTCService.Car newCar)
    {
        return base.Channel.AddCarAsync(newCar);
    }
    
    public void UpdateCar(UTCService.Car newCar)
    {
        base.Channel.UpdateCar(newCar);
    }
    
    public System.Threading.Tasks.Task UpdateCarAsync(UTCService.Car newCar)
    {
        return base.Channel.UpdateCarAsync(newCar);
    }
    
    public void DeleteCar(int id)
    {
        base.Channel.DeleteCar(id);
    }
    
    public System.Threading.Tasks.Task DeleteCarAsync(int id)
    {
        return base.Channel.DeleteCarAsync(id);
    }
}
